### ISSUE TITLE
Question about "${HOME}/.aws/credentials" format

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-ladybug#10]
./docs/test/env.sh 등에서 "${HOME}/.aws/credentials"를 사용하는 것으로 파악됩니다. 스크립트를 보면 대략적으로 작성할 수는 있는데, 혹시 AWS에서 제공하는 credentials 파일인가요?
제가 테스트를 위해 AWS를 통해서 다운로드한 파일은 .csv 형식의 파일이라서 형식이 좀 다릅니다.

**Comment by itnpeople** [comment]
env.sh 파일은 혹시 필요하면 쓰라는 파일이므로 기타에 넣은 것입니다.

$ export KEY="<aws_access_key_id>"
$ export SECRET="<aws_secret_access_key>"

혼란만 준다면 삭제 하는게 좋을듯 하네요.

**Comment by sykim-etri** [comment]
@itnpeople 혹시 AWS CLI에서 자동 생성해 주는 파일 포맷을 예시로 올려주실 수 있으신가요?

**Comment by itnpeople** [comment]
[default]
aws_secret_access_key = y7Ganz6A.................................
aws_access_key_id = AKIA2Z........................
