### ISSUE TITLE
./docs/test/env.sh is not working in zsh

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-ladybug#11]
env.sh가 zsh 환경에서는 정상적으로 동작하지 않습니다.

**Comment by itnpeople** [comment]
env.sh 파일은 혹시 필요하면 쓰라는 파일이므로 기타에 넣은 것입니다.

$ export KEY="<aws_access_key_id>"
$ export SECRET="<aws_secret_access_key>"

혼란만 준다면 삭제 하는게 좋을듯 하네요.

**Comment by sykim-etri** [comment]
혼란을 주지는 않습니다. 개발이나 사용에 도움이 되니 수정하면 되겠습니다.
현재 간단하게 수정한 상황이니 추후 일괄 PR하도록 하겠습니다.

**Comment by sykim-etri** [comment]
Fixed by #17
