### ISSUE TITLE
feature: Implement multi-cloud network overlay

### ISSUE THREAD

**Issue by itnpeople** [cloud-barista/cb-ladybug#20]
* [ ] Implement Kilo

* Kilo
  * multi-cloud network overlay
  * https://github.com/squat/kilo

**Comment by sykim-etri** [comment]
아직 결정된 사항은 아니니 진행은 홀딩 부탁드립니다.

**Comment by sykim-etri** [comment]
현재 ETRI 내부에서 네트워크 이슈를 해결하기 위한 내부 프로젝트(cb-cladnet)가 있습니다. 해당 솔루션이 성공하면 추후 이를 적용할 수 있겠습니다만 현재는 Kilo로 카페모카 릴리즈를 대비하면 되겠습니다.

**Comment by sykim-etri** [comment]
@seokho-son
혹시 hold의 사유가 어떻게 되나요?

**Comment by seokho-son** [comment]
@sykim-etri 지난 코멘트를 보고 hold 요청으로 오해하였습니다. Hold cancel 하였습니다. O_O 확인 감사합니다..^^

**Comment by sykim-etri** [comment]
@seokho-son 
덕분에 hold 아이콘이 있는걸 알게 되었네요..^^
