### ISSUE TITLE
refactor: refactoring source code

### ISSUE THREAD

**Issue by itnpeople** [cloud-barista/cb-ladybug#21]
* [ ] 로그처리 개선
* [ ] Model 소스 개선
* [ ] 유닛 테스트 코드 추가
* [ ] 시작 파라메터, 환경변수 개선
* [ ] REAME, 테스트 shell 현행화
* [ ] 소스 가독성 개선
* [ ] Validation 로직 추가

**Comment by sykim-etri** [comment]
감사합니다.
