### ISSUE TITLE
feat : persistent IP alias configuration

### ISSUE THREAD

**Issue by itnpeople** [cloud-barista/cb-ladybug#35]
bootstrap 개선 건
노드 리부팅시 public-ip 변경에 대한 대응 작업
public-ip 의  ip alias 를 재 정의하고 kubelet 및 설치된 network cni  설정 정보를 업데이트
reboot 시 systemd 활용하여 적용

**Comment by sykim-etri** [comment]
systemd를 활용하여 reboot 문제를 해결하신 것은 굉장히 참신한 방식으로 생각됩니다. 다만 VM reboot 이슈를 CB-Ladybug에서 처리해야 하는 것에 대한 필요성이 명확치 않은 상황입니다. 먼저 필요성을 검토한 후 반영 여부를 결정하도록 하겠습니다.
참고로 새로운 서비스(ladybug-bootstrap.service)를 추가하는 것에 대해서는 부정적인 의견이 있는 상황입니다.

**Comment by sykim-etri** [comment]
@powerkimhub 의견

> systemd 관련해서는,
살펴보니 단순 서비스 등록이네요. 저는 systemd 자체를 특이하게 핸들링하는가 생각했었습니다.
해당 VM이 MCKS 전용이므로 큰 문제는 없을 듯합니다.
위의 restart 등 flow를 점검하시어 VM start(restart, reboot)시 자동으로 control plane 등이 설치되어야 하는 것인지 파악해보시고 결정하면 될 듯합니다. 
다만, service 등록을 해두면 시스템에서 lifecycle 제어는 불편해 보이기는 합니다.
이건, 이슈 발생시 개선해도 될거 같습니다.
