### ISSUE TITLE
Improve attribute names of 'name' and 'uuid' for intuitive usage

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-ladybug#49]
**What would you like to be enhanced**
- API에서 사용되는 name 및 uuid 이름이 사용에 혼란을 줄 수 있음.
- ex) Key로 사용되는 변수는? name or uuid

**Proposed solution**
- Guide 보완 및 Example 추가
- API 변수 개선 등

**Comment by itnpeople** [comment]
ladybug에서 관리되는 메터 데이터 오브젝트는 공통 속성으로 name, kind  속성을 가지고 있습니다.
일반적인 설계 사상으로 판단됩니다.

**Comment by powerkimhub** [comment]
@itnpeople @sykim-etri 

- 해당 이슈는 내부에서 관리되는 정보나 규격에 대한 이슈가 아니었습니다. 사용자 API에 대한 이슈입니다. 
- 아래 이미지와 같은 slack을 통해서 알게된 사항을 단순 정리한 이슈입니다. 
- 내부 구성을 모르는 사용자 입장에서 API와 반환 값만을 이용해서 사용할 때 혼란의 여지가 있는 것 같습니다.
- 사용자가 사용하지 않는 uid라면 제공을(반환을) 안하는 것이 어떤가 싶습니다.
- slack 내용은 다음과 같았습니다. 

![image](https://user-images.githubusercontent.com/46367962/123373046-aa720100-d5bf-11eb-9160-42e029dc6979.png)
