### ISSUE TITLE
Move common const var in test scripts to one file

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-ladybug#72]
**What would you like to be enhanced**
: 
`cb-ladybug/docs/test` 아래에 있는 스크립트들에

```shell
# const
c_URL_LADYBUG="http://localhost:8080/ladybug"
c_CT="Content-Type: application/json"
```
등의 라인이 반복적으로 존재합니다.

- Ladybug Endpoint URL 은 한 테스트 세션 내에서는 일정하게 유지되는 것이 보통일 것이므로
- 각 테스트 스크립트 파일에 존재하면, 수정이 필요할 시 모든 테스트 스크립트 파일을 수정해야 하므로
- ...

각 테스트 스크립트 파일에 존재하는 것 보다는
하나의 파일에 모아 놓는 것이 좋을 것 같습니다.

**Why is this needed**
: 

**Proposed solution**
:
PR #48 에서 `docs/test/conf.env` 이 추가될 예정이므로
위의 라인들을 `docs/test/conf.env` 파일로 옮기고
각 테스트 스크립트 파일에서는 `source ./conf.env` 하여 해당 변수 read

**Comment by sykim-etri** [comment]
새롭게 conf.env가 추가될 예정이니 그것도 좋은 방법 같습니다. #48 이 통합되면 추진하도록 하겠습니다.
감사합니다.
